# Generated by Django 3.2.16 on 2022-11-04 19:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_offered', models.BigIntegerField(default=0)),
                ('learners', models.BigIntegerField(default=0)),
                ('registered_learners', models.BigIntegerField(default=0)),
                ('enrollments', models.BigIntegerField(default=0)),
                ('generated_certificates', models.BigIntegerField(default=0)),
                ('extra_data', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Extra information for instance data')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('processing', 'Processing'), ('generated', 'Generated'), ('error', 'Error')], default='processing', max_length=24)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
