version: 2.1

workflows:
  build:
    jobs:
      - build_edxapp_image:
          filters:
            branches:
              only: Gonzalo/tutor_master

jobs:

  build_edxapp_image:
    docker:
      - image: edxops/focal-common:latest
    steps:

      - run:
          name: Installing Docker CLI
          command: |
            apt update
            apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt install docker-ce-cli=5:19.03.13~3-0~ubuntu-focal -y
    

      - run:
          name: Prepare tutor_distro environment
          command: |
            mkdir -p /tmp/tutor_build /tmp/tutor_build/tutor_root/tutor
            cd /tmp/tutor_build
            echo -e "export TUTOR_ROOT=/tmp/tutor_build/tutor_root/tutor\nexport TUTOR_PLUGINS_ROOT=/tmp/tutor_build/tutor_root/tutor-plugins" >> tutor_env
            git clone -b v11.2.8 https://github.com/overhangio/tutor.git
            virtualenv -p python3.8 /tmp/tutor_build/venv
            source venv/bin/activate
            cd tutor && pip install -e . && cd ..
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone -b stage git@bitbucket.org:edunext/plugin-distro-ednx.git
            pip install -e ./plugin-distro-ednx

      - run:
          name: Enable tutor_distro plugins
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            tutor plugins enable distro_ednx

      - run:
          name: Creating tutor config
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            tutor plugins list
            tutor config save

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Building openedx image with tutor_distro
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            main_repo_url="<< pipeline.project.git_url >>.git"
            main_repo_branch="<< pipeline.git.branch >>"
            tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=$main_repo_url --build-arg EDX_PLATFORM_VERSION=$main_repo_branch
      
      - run:
          name: Pushing openedx image to Docker Registry with tutor_distro
          working_directory: /tmp/tutor_build
          command: |
            source tutor_env
            source venv/bin/activate
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            tutor images push openedx
  