version: 2.1

workflows:
  build:
    jobs:
      - build_edxapp_image:
          filters:
            branches:
              only: Gonzalo/tutor_master
jobs:
  build_edxapp_image:
    docker:
      - image: edxops/focal-common:latest
    environment:
      TUTOR_ROOT: "tmp/tutor_build/tutor_root/tutor"
      TUTOR_PLUGINS_ROOT: "/tmp/tutor_build/tutor_root/tutor-plugins"

    steps:

      - run:
          name: Installing Docker CLI
          command: |
            apt update
            apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt install docker-ce-cli=5:19.03.13~3-0~ubuntu-focal -y
    

      - run:
          name: Prepare tutor_distro environment
          command: |
            mkdir -p /tmp/tutor_build /tmp/tutor_build/tutor_root/tutor
            cd /tmp/tutor_build
            git clone -b v11.2.9 https://github.com/overhangio/tutor.git
            cd tutor && pip install -e . && cd ..
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" pip install git+ssh://git@bitbucket.org/edunext/plugin-distro-ednx.git@stage#egg=plugin-distro-ednx==stage

      - run:
          name: Enable tutor_distro plugins
          working_directory: /tmp/tutor_build
          command: |
            tutor plugins enable distro_ednx

      - run:
          name: Creating tutor config
          working_directory: /tmp/tutor_build
          command: |
            tutor plugins list
            tutor config save

      # - setup_remote_docker:
      #     version: 19.03.13
      #     docker_layer_caching: true

      # - run:
      #     name: Building openedx image with tutor_distro
      #     working_directory: /tmp/tutor_build
      #     command: |
      #       main_repo_url="<< pipeline.project.git_url >>.git"
      #       main_repo_branch="<< pipeline.git.branch >>"
      #       tutor images build openedx --build-arg EDX_PLATFORM_REPOSITORY=$main_repo_url --build-arg EDX_PLATFORM_VERSION=$main_repo_branch
      
      # - run:
      #     name: Pushing openedx image to Docker Registry with tutor_distro
      #     working_directory: /tmp/tutor_build
      #     command: |
      #       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      #       tutor images push openedx

      # - run:
      #     name: Building openedx dev image 
      #     working_directory: /tmp/tutor_build
      #     command: |
      #       tutor images build openedx-dev
            
      
      # - run:
      #     name: Pushing openedx dev image to Docker Registry with tutor_distro
      #     working_directory: /tmp/tutor_build
      #     command: |
      #       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      #       docker p.circleci/config.ymlush docker.io/ednxops/ednx_distro_edxapp_dev:latest


      # ESTE BLOQUE FUE CREADO SOLO CON FINES DE PRUEBA
      # - attach_workspace:
      #     at: /tmp/workspace
      
      # - run : |
      #     TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
      #     git clone https://github.com/NeOneSoft/ArgoCD-Test-1 tmp/ArgoCD-Test1
      #     cd tmp/ArgoCD-Test1
      #     cp tmp/workspace/deployment-1.yaml .
      #     sed -i 's/\(circleci-webappdemo\)\(.*\)/\1:'$TAG'/' ./deployment-1.yaml
      #     git config --global user.email "gonzalo.romero@edunext.co"
      #     git config --global user.name "NeOneSoft"
      #     git add .
      #     git commit -m "New UPDATE via CircleCI to create new yaml files"
      #     # Push quietly to a new repository adding files
      #     git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/NeOneSoft/ArgoCD-Test-1.git main

      - run : 
          name: Generate files to ArgoCD
          working_directory: /tmp/tutor_build
          command: |
            TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
            GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone -b eric/distro_0-1 git@bitbucket.org:edunext/ops-distro-ednx.git
            cp tmp/tutor_build/tutor_root/tutor/config.yml .
            sed -i 's/\(tutor-CICD\)\(.*\)/\1:'$TAG'/' ./config.yml
            git config --global user.email "gonzalo.romero@edunext.co"
            git config --global user.name "GoNeoSoft"
            git add .
            git commit -m "New UPDATE via CircleCI to create new yaml files"
            # Push quietly to a new repository adding files
            git push -q https://$GITHUB_PERSONAL_TOKEN@bitbucket.org/ops-distro-ednx.git 
