version: 2.1

workflows:
  build:
    jobs:
      - build_edxapp_image:
          filters:
            branches:
              only: Gonzalo/tutor_master

jobs:

  build_edxapp_image:
    docker:
      - image: edxops/focal-common:latest
    steps:

      - run:
          name: Installing Docker CLI
          command: |
            apt update
            apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt install docker-ce-cli=5:19.03.13~3-0~ubuntu-focal -y

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
