name: CI
on:
  push:
    branches:
      - Gonzalo/unit_tests_github_actions

jobs:
  run-tests:
    # continue-on-error: true
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: ["2.2"]
        test_module: ["lms"]


    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }} ${{ matrix.test_module }}
    steps:
      # - run: sudo su
      - uses: actions/checkout@v2
      # - name: start mongodb service
      #   run: |
      #     sudo /etc/init.d/mongodb start
      - name: install requirements
        run: |
          sudo pip install -r requirements/pip.txt
          sudo pip install -r requirements/edx/testing.txt
          sudo pip install "django~=${{ matrix.django-version }}.0"
      - name: run tests
        run: |
          pytest ${{ matrix.test_module }}
