name: verify unit tests count

on:
  - pull_request

jobs:
  collect-and-verify:
    runs-on: [ edx-platform-runner ]
    steps:
      - name: sync directory owner
        run: sudo chown runner:runner -R .*

      - uses: actions/checkout@v2
      - name: install requirements
        run: |
          sudo make test-requirements

      - name: verify unit tests count
        uses: ./.github/actions/verify-tests-count
